const mongoose = require("mongoose");

const cadastroSchema = new mongoose.Schema({
    nomeCompleto: String,
    nomeDaMae: String,
    nomeDoPai: String,
    naturalidade: String,
    nacionalidade: String,
    idade: Number,
    dataDeNascimento: String,
    estadoCivil: String,
    raca: String,
    escolaridade: String,
    profissao: String,
    CPF: String,
    sexo: String,
    RG: String,
    estadoEmissor: String,
    dataDeEmissaoRG: String,
    orgaoEmissor: String,
    CEP: String,
    endereco: String,
    estado: String,
    municipio: String,
    bairro: String,
    unidadeDeOrigem: String,
    numeroDeInternacoes: Number,
    contatoDeEmergencia1: String,
    contatoDeEmergencia2: String,
    dataDeSaida: String,
    matricula: String,
    possuiFilhos: Boolean,
    situacaoDeRua: Boolean,
    tempoDeRua: String,
    tempoDeDrogadicao: String,
    tiposDeDrogas: String,
    usaMedicamentos: Boolean,
    doencasCuidados: Boolean,
    alergia: Boolean,
    acompanhamentoPsiquiatrico: Boolean,
    respondeProcesso: Boolean,
    recebeBeneficio: Boolean,
    religiao: String,
    igrejaEvangelica: Boolean,
    batizado: Boolean,
    casaDeRecuperacao: Boolean,
    jaFoiAcolhido: Boolean,
    deficiencia: Boolean,
    antecedentesCriminais: Boolean,
    fazNasHorasVagas: String,
    consideracoesDeAtendimento: String
});

const cadastroModel = mongoose.model("acolhido", cadastroSchema);

module.exports = { cadastroModel, cadastroSchema };
